/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat_Project.chatApp;

import Chat_Project.messagePackage.Message;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;

/**
 *
 * @author Dell
 */
public class ChatMain extends javax.swing.JFrame {

    ChatCellRenderer chatCellRender;
    ChatCellRenderer groupCellRender;

    void refreshGroups() {
        grupsModel.removeAllElements();
        for (Group myGroup : me.myGroups) {
            grupsModel.addElement(myGroup);
        }
        currentGroup = me.myGroups.get(0);
    }

    DefaultListModel chatsModel = new DefaultListModel();
    DefaultListModel currentChatModel = new DefaultListModel();
    DefaultListModel grupsModel = new DefaultListModel();
    DefaultListModel tempChatsModel = new DefaultListModel();
    DefaultListModel groupChatModel = new DefaultListModel();
    DefaultListModel groupContactsModel = new DefaultListModel();

    public ChatMain() {
        initComponents();
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        tempChatsList.setSize(250, 150);
        grupsList.setSize(250, 130);
        chatsList.setModel(chatsModel);
        currentChatList.setModel(currentChatModel);
        grupsList.setModel(grupsModel);
        tempChatsList.setModel(tempChatsModel);
        groupChatList.setModel(groupChatModel);
        groupContactsList.setModel(groupContactsModel);

        chatCellRender = new ChatCellRenderer();
        currentChatList.setCellRenderer(chatCellRender);

        groupCellRender = new ChatCellRenderer();
        groupChatList.setCellRenderer(groupCellRender);

        ProfileCellRenderer pcr = new ProfileCellRenderer("profile_smaller.png");
        chatsList.setCellRenderer(pcr);
        tempChatsList.setCellRenderer(pcr);
        groupContactsList.setCellRenderer(pcr);
        grupsList.setCellRenderer(new ProfileCellRenderer("group.png"));
        //groupChatList.setCellRenderer(new ChatCellRenderer());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        icones_panel = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l11 = new javax.swing.JLabel();
        l12 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        l16 = new javax.swing.JLabel();
        l17 = new javax.swing.JLabel();
        l18 = new javax.swing.JLabel();
        l19 = new javax.swing.JLabel();
        l20 = new javax.swing.JLabel();
        l21 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatsList = new javax.swing.JList<>();
        connectBtn = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tempChatsList = new javax.swing.JList<>();
        createGrupBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        grupsList = new javax.swing.JList<>();
        groupName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentChatList = new javax.swing.JList<>();
        message_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rivalName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        profile1 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        myNameLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        groupChatList = new javax.swing.JList<>();
        group_msg_text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        groupContactsList = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        currentGroupLabel = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        border_group = new javax.swing.JLabel();
        profile_group = new javax.swing.JLabel();
        profile2 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        myNameLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPopupMenu1.setBorderPainted(false);
        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu1.setDoubleBuffered(true);

        icones_panel.setLayout(new java.awt.GridBagLayout());

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/11x.png"))); // NOI18N
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l1, gridBagConstraints);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/12x.png"))); // NOI18N
        l2.setLabelFor(l1);
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l2, gridBagConstraints);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/13x.png"))); // NOI18N
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l3, gridBagConstraints);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/15x.png"))); // NOI18N
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l5, gridBagConstraints);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/18x.png"))); // NOI18N
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l4, gridBagConstraints);

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/22x.png"))); // NOI18N
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l7, gridBagConstraints);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/4x.png"))); // NOI18N
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l6, gridBagConstraints);

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/2x.png"))); // NOI18N
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l8, gridBagConstraints);

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/3x.png"))); // NOI18N
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l9, gridBagConstraints);

        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/14x.png"))); // NOI18N
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l10, gridBagConstraints);

        l11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/20x.png"))); // NOI18N
        l11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l11, gridBagConstraints);

        l12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/19x.png"))); // NOI18N
        l12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l12, gridBagConstraints);

        l13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/1x.png"))); // NOI18N
        l13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l13, gridBagConstraints);

        l14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/16x.png"))); // NOI18N
        l14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l14, gridBagConstraints);

        l15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/17x.png"))); // NOI18N
        l15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l15, gridBagConstraints);

        l16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/21x.png"))); // NOI18N
        l16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l16, gridBagConstraints);

        l17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/5x.png"))); // NOI18N
        l17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l17, gridBagConstraints);

        l18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/6x.png"))); // NOI18N
        l18.setToolTipText("");
        l18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l18, gridBagConstraints);

        l19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/7x.png"))); // NOI18N
        l19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l19, gridBagConstraints);

        l20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/8x.png"))); // NOI18N
        l20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l20, gridBagConstraints);

        l21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/9x.png"))); // NOI18N
        l21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l1MousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        icones_panel.add(l21, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(540, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        chatsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chatsListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(chatsList);

        connectBtn.setText("Connect");
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        tempChatsList.setFocusCycleRoot(true);
        tempChatsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tempChatsListMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tempChatsList);

        createGrupBtn.setText("Create grup");
        createGrupBtn.setEnabled(false);
        createGrupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGrupBtnActionPerformed(evt);
            }
        });

        grupsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grupsListMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(grupsList);

        groupName.setEnabled(false);
        groupName.setVerifyInputWhenFocusTarget(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/refresh.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(connectBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameText))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(createGrupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)))
                    .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(groupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(connectBtn)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createGrupBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main Page", jPanel1);

        jScrollPane2.setViewportView(currentChatList);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/emoji_click.png"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setComponentPopupMenu(jPopupMenu1);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/add.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/border_small.png"))); // NOI18N
        jLayeredPane1.add(jLabel6);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/profile_small.png"))); // NOI18N
        jLayeredPane1.add(jLabel5);

        rivalName.setFont(new java.awt.Font("Khmer SBBIC Serif", 1, 13)); // NOI18N
        rivalName.setForeground(new java.awt.Color(51, 51, 51));
        rivalName.setText("Friend Name");

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(rivalName, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rivalName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/send_click.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        profile1.setLayout(new javax.swing.BoxLayout(profile1, javax.swing.BoxLayout.LINE_AXIS));

        jLayeredPane3.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane3.setLayout(new javax.swing.OverlayLayout(jLayeredPane3));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/border_small.png"))); // NOI18N
        jLayeredPane3.add(jLabel8);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/profile_small.png"))); // NOI18N
        jLayeredPane3.add(jLabel9);

        profile1.add(jLayeredPane3);

        jLabel15.setText("     ");
        profile1.add(jLabel15);

        myNameLabel.setFont(new java.awt.Font("Khmer SBBIC Serif", 1, 13)); // NOI18N
        myNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        myNameLabel.setText("Your Name");
        profile1.add(myNameLabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(profile1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(message_txt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(282, 282, 282))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20)
                .addComponent(profile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Current Chat", jPanel2);

        jScrollPane5.setViewportView(groupChatList);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/add.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/send_click.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        groupContactsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                groupContactsListMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(groupContactsList);

        currentGroupLabel.setFont(new java.awt.Font("Khmer SBBIC Serif", 1, 13)); // NOI18N
        currentGroupLabel.setForeground(new java.awt.Color(51, 51, 51));
        currentGroupLabel.setText("Group Name");

        jLayeredPane2.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane2.setLayout(new javax.swing.OverlayLayout(jLayeredPane2));

        border_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/border_small.png"))); // NOI18N
        jLayeredPane2.add(border_group);

        profile_group.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/group_big.png"))); // NOI18N
        jLayeredPane2.add(profile_group);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(currentGroupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        profile2.setLayout(new javax.swing.BoxLayout(profile2, javax.swing.BoxLayout.LINE_AXIS));

        jLayeredPane4.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane4.setLayout(new javax.swing.OverlayLayout(jLayeredPane4));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/border_small.png"))); // NOI18N
        jLayeredPane4.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/profile_small.png"))); // NOI18N
        jLayeredPane4.add(jLabel11);

        profile2.add(jLayeredPane4);

        jLabel14.setText("     ");
        profile2.add(jLabel14);

        myNameLabel1.setFont(new java.awt.Font("Khmer SBBIC Serif", 1, 13)); // NOI18N
        myNameLabel1.setForeground(new java.awt.Color(51, 51, 51));
        myNameLabel1.setText("Your Name");
        profile2.add(myNameLabel1);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chat_Project/images/emoji_click.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(profile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(group_msg_text)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(group_msg_text, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Current Group", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Client me;
    Thread myThread;
    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
        if (!nameText.getText().equals("")) {
            jButton1.setEnabled(true);
            nameText.setEditable(false);
            nameText.setBackground(Color.GREEN);
            myThread = this.createMyThread();
            myThread.start();
        } else {
            JOptionPane.showConfirmDialog(this, "Enter your name!", "Alert", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_connectBtnActionPerformed
    Chat currentChat = null;
    private void chatsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chatsListMousePressed
        int index = chatsList.getSelectedIndex();
        if (index != -1) {
            currentChat = chatsList.getSelectedValue();
            jTabbedPane1.setSelectedIndex(1);
            rivalName.setText(currentChat.getName());
            currentChat.reloadChat();
            chatCellRender.refresh(currentChat);
            currentChatList.repaint();
            jTabbedPane1.setEnabledAt(1, true);
        }
    }//GEN-LAST:event_chatsListMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (me != null) {
            me.Send(null, Message.Message_Type.Disconnect);
            myThread.stop();
            me.Stop();
        }
    }//GEN-LAST:event_formWindowClosing

    private void createGrupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGrupBtnActionPerformed
        if (tempChatsList.getSelectedIndex() != -1 && !groupName.getText().equals("")) {
            String grup_name = groupName.getText();
            ArrayList<String[]> temp = new ArrayList<>();
            String[] gpName = {"", grup_name};
            temp.add(gpName);
            String[] c = {"" + me.myID, me.myName};
            temp.add(c);
            ArrayList<Chat> contacts = (ArrayList<Chat>) tempChatsList.getSelectedValuesList();

            for (int j = 0; j < tempChatsList.getSelectedIndices().length; j++) {
                String[] x = {"" + contacts.get(j).getId(), contacts.get(j).getName()};
                temp.add(x);
            }
            //contacts.set(0, new Chat(me.myID, me.myName, currentChatModel));
            Group group = new Group(grup_name, contacts, groupChatModel, me);
            me.myGroups.add(group);
            refreshGroups();
            gpName[0] = "" + group.id;
            temp.set(0, gpName);
            me.Send(temp.clone(), Message.Message_Type.newGroup);
            createGrupBtn.setEnabled(false);
            groupName.setEnabled(false);
            groupName.setText("");
        } else {
            JOptionPane.showConfirmDialog(this, "You should select the contacts and enter the group name!", "Alert", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_createGrupBtnActionPerformed
    Group currentGroup = null;
    private void grupsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupsListMousePressed
        // TODO add your handling code here:
        int index = grupsList.getSelectedIndex();
        if (index != -1) {
            currentGroup = grupsList.getSelectedValue();
            groupCellRender.refresh(currentGroup);
            jTabbedPane1.setSelectedIndex(2);
            currentGroupLabel.setText(currentGroup.toString());
            currentGroup.reloadGroup();
            groupContactsModel.removeAllElements();
            for (Chat contact : currentGroup.getContacts()) {
                groupContactsModel.addElement(contact);
            }
            jTabbedPane1.setEnabledAt(2, true);
        }
    }//GEN-LAST:event_grupsListMousePressed
    JLabel label = null;
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        jPopupMenu1.add(icones_panel);
        jPopupMenu1.show(this, 135, 165);
    }//GEN-LAST:event_jLabel1MousePressed

    private void l1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseEntered
        label = (JLabel) evt.getSource();
        label.setBorder(new BevelBorder(0, Color.GREEN, Color.GREEN, Color.GREEN, Color.GREEN));
    }//GEN-LAST:event_l1MouseEntered

    private void l1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseExited
        label = (JLabel) evt.getSource();
        label.setBorder(null);
    }//GEN-LAST:event_l1MouseExited

    private void l1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MousePressed
        String[] path = label.getIcon().toString().split("/");
        if (jTabbedPane1.getSelectedIndex() == 1) {
            Object[] yt = {currentChat.getId(), path[path.length - 1], currentChatList.getLastVisibleIndex() + 1};
            me.Send(yt.clone(), Message.Message_Type.icon_ms);
            currentChat.sendIconToThisChat(currentChatList.getLastVisibleIndex() + 1, label.getIcon());
            chatCellRender.refresh(currentChat);
            currentChatList.repaint();
        } else {
            System.out.println("2 selected");
            //me.Send(currentGroup.createFileMessage(file, f.getName()), Message.Message_Type.file_msg_group);
            me.Send(currentGroup.createIconMessage(path[path.length - 1]), Message.Message_Type.icon_ms_group);
            currentGroup.sendIconToThisGroup(groupChatList.getLastVisibleIndex() + 1, label.getIcon());
            groupCellRender.refresh(currentGroup);
            groupChatList.repaint();
        }

    }//GEN-LAST:event_l1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        File f = Utils.chooseFile(this);
        byte[] file = Utils.prepareFileToSend(f.getAbsolutePath());
        Object[] d = {f.getName(), file, currentChat.getId()};
        me.Send(d, Message.Message_Type.file_msg);
        currentChat.sendFileIconToThisChat(currentChat.getChatContent().size(), Utils.decideFileIcon(f.getName()));
        currentChat.sendMessageToThisChat("You-> " + f.getName());
        chatCellRender.refresh(currentChat);
        currentChatList.repaint();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        File f = Utils.chooseFile(this);
        byte[] file = Utils.prepareFileToSend(f.getAbsolutePath());
        me.Send(currentGroup.createFileMessage(file, f.getName()), Message.Message_Type.file_msg_group);
        currentGroup.sendFileIconToThisGroup(currentGroup.getChatContent().size(), Utils.decideFileIcon(f.getName()));
        currentGroup.sendMessageToThisGroup("You-> " + f.getName());
        groupCellRender.refresh(currentGroup);
        groupChatList.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void tempChatsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempChatsListMousePressed
        if (tempChatsList.getSelectedIndex() > -1) {
            groupName.setEnabled(true);
        }
    }//GEN-LAST:event_tempChatsListMousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        String msg = group_msg_text.getText();
        me.Send(currentGroup.createMessage(msg), Message.Message_Type.TextGroup);
        currentGroup.sendMessageToThisGroup("You->" + msg);
        group_msg_text.setText("");
    }//GEN-LAST:event_jLabel4MousePressed

    private void groupContactsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupContactsListMousePressed
        int index = groupContactsList.getSelectedIndex();
        if (index != -1) {
            jTabbedPane1.setEnabledAt(1, true);
            currentChat = groupContactsList.getSelectedValue();
            jTabbedPane1.setSelectedIndex(1);
            rivalName.setText("Name: " + currentChat.getName());
            currentChat.reloadChat();
            chatCellRender.refresh(currentChat);
            currentChatList.repaint();
        }
    }//GEN-LAST:event_groupContactsListMousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        me.Send(new String[]{currentChat.getId() + "", message_txt.getText()}, Message.Message_Type.Text);
        currentChat.sendMessageToThisChat("You->" + message_txt.getText());
        message_txt.setText("");
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        jPopupMenu1.add(icones_panel);
        jPopupMenu1.show(this, 125, 190);
    }//GEN-LAST:event_jLabel12MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x = 0;
        tempChatsModel.removeAllElements();
        for (Chat chat : me.myChats) {
            tempChatsModel.addElement(chat);
            x++;
        }
        if (x > 0) {
            createGrupBtn.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    Thread createMyThread() {
        me = new Client();
        myNameLabel.setText(nameText.getText());
        myNameLabel1.setText(nameText.getText());
        me.myName = nameText.getText();
        connectBtn.setEnabled(false);
        Thread thread = new Thread(() -> {
            // client oluştur
            // servera bağlan
            me.Start("184.72.69.97", 2000);
            me.Send(nameText.getText(), Message.Message_Type.Connect);
            while (me.socket.isConnected()) {
                try {
                    Message received = (Message) (me.sInput.readObject());
                    switch (received.type) {
                        case Connect:
                            me.myID = (int) received.content;
                            break;
                        case Refresh:
                            chatsModel.removeAllElements();
                            Utils.refreshContactsList(me, (ArrayList<String[]>) received.content, currentChatModel);
                            me.reloadMyContacts(chatsModel);
                            break;
                        case Disconnect:
                            chatsModel.removeAllElements();
                            Utils.refreshContactsListDisconnect(me, (ArrayList<String[]>) received.content);
                            me.reloadMyContacts(chatsModel);
                            break;
                        case Text:
                            String[] message = (String[]) received.content;
                            int id = Integer.parseInt(message[0]);
                            String content = message[1];
                            System.out.println(id + " " + content);
                            for (Chat myChat : me.myChats) {
                                if (myChat.getId() == id) {
                                    if (currentChat == null) {
                                        myChat.receiveMessageFromThisChat(myChat.getName() + "->" + content, -1);
                                    } else {
                                        myChat.receiveMessageFromThisChat(myChat.getName() + "->" + content, currentChat.getId());
                                    }

                                    break;
                                }
                            }
                            break;
                        case newGroup:
                            ArrayList<String[]> groupInfo = (ArrayList) received.content;
                            int groupId = Integer.parseInt(groupInfo.get(0)[0]);
                            String groupName = groupInfo.get(0)[1];
                            ArrayList<Chat> groupChats = new ArrayList<>();
                            Chat groupCreater = null;
                            for (int j = 1; j < groupInfo.size(); j++) {
                                int idx = Integer.parseInt(groupInfo.get(j)[0]);
                                String name = groupInfo.get(j)[1];

                                for (Chat myChat : me.myChats) {
                                    if (idx == myChat.getId()) {
                                        groupChats.add(myChat);
                                        break;
                                    }
                                }

//                                System.out.println(idx + " -> " + name);
                            }
                            Group gp = new Group(groupName, groupId, groupChats, groupChatModel, groupCreater);
                            me.myGroups.add(gp);
                            refreshGroups();
                            break;
                        case TextGroup:
                            String[] messageGroup = (String[]) received.content;
                            String sender_name = messageGroup[0];
                            int group_id = Integer.parseInt(messageGroup[1]);
                            String messageGroup_content = messageGroup[2];
                            for (Group myGroup : me.myGroups) {
                                if (myGroup.getThisGroupId() == group_id) {
                                    myGroup.receiveMessageFromThisGroup(sender_name + "-> " + messageGroup_content, currentGroup.getThisGroupId());
                                }
                            }

                            break;
                        case file_msg:
                            Object[] file_info = (Object[]) received.content;
                            Utils.receiveFile((byte[]) file_info[1], (String) file_info[0]);
                            int file_sender_id = (int) file_info[2];
                            for (Chat myChat : me.myChats) {
                                if (myChat.getId() == file_sender_id) {
                                    if (currentChat == null) {
                                        myChat.receiveFileIconFromThisChat(myChat.getChatContent().size(), Utils.decideFileIcon((String) file_info[0]));
                                        myChat.receiveMessageFromThisChat(myChat.getName() + "-> " + (String) file_info[0], -1);

                                    } else {
                                        myChat.receiveFileIconFromThisChat(myChat.getChatContent().size(), Utils.decideFileIcon((String) file_info[0]));
                                        myChat.receiveMessageFromThisChat(myChat.getName() + "-> " + (String) file_info[0], currentChat.getId());

                                        chatCellRender.refresh(currentChat);
                                        currentChatList.repaint();
                                    }

                                    break;
                                }
                            }

                            break;
                        case icon_ms:
                            Object[] recived_icon = (Object[]) received.content;
                            String icon_name = (String) recived_icon[1];

                            ImageIcon icon = Utils.getIcon(icon_name);
                            for (Chat myChat : me.myChats) {
                                if (myChat.getId() == (Integer) recived_icon[0]) {
                                    if (currentChat == null) {
                                        myChat.receiveIconFromThisChat((Integer) recived_icon[2], icon, -1);
                                    } else {
                                        myChat.receiveIconFromThisChat((Integer) recived_icon[2], icon, currentChat.getId());
                                        chatCellRender.refresh(currentChat);
                                        currentChatList.repaint();
                                    }
                                    break;
                                }
                            }
                            break;
                        case file_msg_group:
                            //Object[]{this.name, file_info.get(0), file_name, file_content}
                            Object[] fileMsg = (Object[]) received.content;
                            int group__id = Integer.parseInt((String) fileMsg[1]);
                            String senderName = (String) fileMsg[0];
                            String fileMsgName = group__id + "_" + (String) fileMsg[0] + "_" + me.myName + "_" + (String) fileMsg[2];
                            String file_name = (String) fileMsg[2];
                            Utils.receiveFile((byte[]) fileMsg[3], fileMsgName);
                            int senderId = (int) fileMsg[4];
                            for (Group myGroup : me.myGroups) {
                                if (myGroup.getThisGroupId() == group__id) {
                                    if (currentGroup == null) {
                                        myGroup.receiveFileIconFromThisGroup(myGroup.getChatContent().size(), Utils.decideFileIcon(file_name));
                                        myGroup.receiveMessageFromThisGroup((String) fileMsg[0] + "-> " + file_name, -1);

                                    } else {
                                        myGroup.receiveFileIconFromThisGroup(myGroup.getChatContent().size(), Utils.decideFileIcon(file_name));
                                        myGroup.receiveMessageFromThisGroup((String) fileMsg[0] + "-> " + file_name, currentGroup.getThisGroupId());

                                        groupCellRender.refresh(currentGroup);
                                        groupChatList.repaint();
                                    }

                                    break;
                                }
                            }
                            break;
                        case icon_ms_group:
                            //{sender_name, GroupId, icon_name};
                            Object[] iconMsg = (Object[]) received.content;
                            String sender_nm = (String) iconMsg[0];
                            String icon_nm = (String) iconMsg[2];
                            int gr_id = (int) iconMsg[1];
                            for (Group myGroup : me.myGroups) {
                                if (myGroup.getThisGroupId() == gr_id) {
                                    if (currentGroup == null) {
                                        myGroup.receiveIconFromThisGroup(sender_nm, Utils.getIcon(icon_nm), -1);

                                    } else {
                                        myGroup.receiveIconFromThisGroup(sender_nm, Utils.getIcon(icon_nm), currentGroup.getThisGroupId());
                                        currentGroup.reloadGroup();
                                        groupCellRender.refresh(currentGroup);
                                        groupChatList.repaint();
                                    }

                                    break;
                                }
                            }
                            break;
                    }

                } catch (IOException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                    //Client.Stop();
                    break;
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                    //Client.Stop();
                    break;
                }
            }
        });
        return thread;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel border_group;
    private javax.swing.JList<Chat> chatsList;
    private javax.swing.JButton connectBtn;
    private javax.swing.JButton createGrupBtn;
    private javax.swing.JList<String> currentChatList;
    private javax.swing.JLabel currentGroupLabel;
    private javax.swing.JList<String> groupChatList;
    private javax.swing.JList<Chat> groupContactsList;
    private javax.swing.JTextField groupName;
    private javax.swing.JTextField group_msg_text;
    private javax.swing.JList<Group> grupsList;
    private javax.swing.JPanel icones_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l19;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l20;
    private javax.swing.JLabel l21;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextField message_txt;
    private javax.swing.JLabel myNameLabel;
    private javax.swing.JLabel myNameLabel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel profile1;
    private javax.swing.JPanel profile2;
    private javax.swing.JLabel profile_group;
    private javax.swing.JLabel rivalName;
    private javax.swing.JList<Chat> tempChatsList;
    // End of variables declaration//GEN-END:variables
}
